### ISSUE TITLE
Length of videos is incorrect

### ISSUE THREAD

**Issue by Dikowda** [thecoder75/liveme-tools#102] opened 2017-11-09 19:38 UTC
**v6.2.1**:
**Windows**:

Great work!
Small thing but it bugs me.  The Length of videos appears to be incorrect.  I assume it is a conversion from 'length' returned in POST which is in seconds.  Typical example which is 1229 seconds long but length is displayed as 20:09 but should be 20:29.  Calculation is 1229/60=20.48 minutes & 0.48*60=29 seconds.

**Comment by polydragon** [comment] 2017-11-09 19:52
Related to #95

**Comment by zp** [comment] 2017-11-09 21:29
I've noticed some videos have different lengths on the replay info page vs the hls video player.

If you download the video and play it in your regular video player, does it show the expected 20:29 length?

**Comment by Dikowda** [comment] 2017-11-09 22:29
Yes the example I gave shows 20:29 in Pot player and MPlayer.  WMP and VLC say 20:27 though.

**Comment by Dikowda** [comment] 2017-11-09 22:40
Oops, sorry. I was looking at the raw .ts file.  When downloaded and converted to .mp4 via LiveMeTools all media players say 20:29.

**Comment by zp** [comment] 2017-11-09 23:53
Okay I see, you talking about the length that's shown on the search info and NOT in the built in hls player correct?

Cause the built in hls player should be showing 20:29 as expected when you play the video, but the search / replay info for videos is showing a different value, which is an easy fix.

**Comment by Dikowda** [comment] 2017-11-10 07:58
Yes, its the display on the search results.

**Comment by polydragon** [comment] 2017-11-10 11:02
I've swapped the parsing of the time over to `format-duration`, like #95. This solves some edge cases in the processing of it, however when doing a hashtag search I've noticed that all the values are always wrong (at least for the ones I found using it.) Maybe they're sending the wrong value or the playlist files aren't complete. It will need some more investigation to see if it's anything we can fix.

**Comment by zp** [comment] 2017-11-10 11:21
Most of the video's that I've seen with incorrect durations are on the myqcloud CDN.

The cause is most likely due to the myqcloud CDN being absolute shit and messing up the actual video files 90% of the time, but the API is showing the live stream run time.

Videos on ksmobile return the proper duration the vast majority of the time.

**Comment by thecoder75** [comment] 2017-11-16 18:01
I agree with @zp on this and now see things are working to the best of what we can rely on based on the data fetched from Live.me and am going to close this ticket for now.

Maybe some day when Live.me addresses all their issues and we all win money on the lottery and when.... then we'll revisit this issue.

**Closed by thecoder75** 2017-11-16 18:01 UTC
Labels: bug
