### ISSUE TITLE
Massive one - 6.05 downloads not working !!

### ISSUE THREAD

**Issue by thegeezer9999** [thecoder75/liveme-tools#67] opened 2017-09-28 03:45 UTC
Latest version, pick download a video, Seems to flash up in Q quickly, but nothing downloads !! Aaargh - just wasted 4 hours :-(

Might have something to do with the error on close (Note cannot close program - have to kill task)

W10 X64 using Wx64 version

No downloads on any version 6.0x
Download same video OK and create download Q on 5.09

Suspect the buffer may not be sufficient on new build ?

![image](https://user-images.githubusercontent.com/32274697/30948261-93f21756-a406-11e7-94c2-ee11f000b76e.png)

Can this please be addressed - I think this classes as critical.

**Comment by polydragon** [comment] 2017-09-28 15:23
Downloads:
I really have no idea what Coder is doing with regards to the downloader, it's confusing to try to keep track of it all and I'll have to ask him about it. As far as I know downloads worked perfectly in the 5.0.9 release for everyone that I've asked, and 6.0.x has only caused more problems.

For now this is how to fix it.

1. Open up the directory containing the `liveme-tools.exe` for the `5.0.9` release.
2. Move into the `resources` directory.
3. Copy the `ffmpeg.exe` file.
4. Open up the directory containing the `liveme-tools.exe` for the `6.0.5` release.
5. Paste the `ffmpeg.exe` file next to the `liveme-tools.exe` for the `6.0.5` release (do **not** put it in the `resources` directory)
6. Restart the 6.0.5 release and try again, it should work now.

Error:
I haven't seen that from anyone else and I'm not getting that issue personally, but I'll double check the code to see what could possibly cause it. How are you trying to close the app? The windows close button or through File -> Quit?

**Comment by thecoder75** [comment] 2017-09-28 17:06
I was hoping to move away from bundling/including FFMPEG with the builds as on one OS it worked as intended but broke on another.  I was never able to find a fully successful way of doing it short of having FFMPEG installed in a folder in the path.

May have to bundle it differently based on OS to get it to work but so far haven't found a one-way fits all solution yet.  Hopefully polydragon can test different solutions on Windows and maybe Linux for now and I'll try and test his solutions on macOS when I can.

**Comment by zp** [comment] 2017-09-29 05:02
Have you looked at https://www.npmjs.com/package/@ffmpeg-installer/ffmpeg?

Seems like it could be a decent solution.

**Comment by polydragon** [comment] 2017-09-29 09:30
Already used it before, though it didn't seem to work on Mac. I can't really test it there.

thecoder75: I can't really test any other solutions for Windows and Linux because the ones we have tried before have worked perfectly on these systems anyway. I don't know what's wrong with the Mac version that's so different that makes none of the solutions we've used work.

**Comment by thecoder75** [comment] 2017-09-29 15:24
I've found that macOS is very picky on where FFMPEG is installed.  I've had it work smoothly one time, then fail 5 times in a row then work again.  As far as I know there is only one Mac user and he's reported similar things to me as well.

We can add FFMPEG back to the build process and include it on Windows versions and provide instructions for now for the Mac and Linux users on how to manually install and go from there, that I have no problem doing.  And from my testing on Kubuntu, I had no failures either using the Repository installed version of FFMPEG.   It's just the Mac version that keeps having issues.

**Comment by polydragon** [comment] 2017-09-30 20:16
Fixed in 6.0.6.

**Closed by polydragon** 2017-09-30 20:16 UTC
Labels: unconfirmed-bug
