### ISSUE TITLE
merging chunks doesn't finish

### ISSUE THREAD

**Issue by Hopeful13** [thecoder75/liveme-tools#111] opened 2017-11-21 03:50 UTC
v7.0.1
Windows 10 64bit
**Subsystem**: 

Hey. Thanks for this new 7.0 version it's much better than previous releases with very fast downloads where previously download was so slow. Liking it. 
I've run into an issue though some streams that are longer in length like 30min to an hour i'm finding gets stuck on "merging chunks" after the download finishes and it attempts to merge the file. If you empty que then the following downloads after this added to the download que stay in the waiting position and the only way to get things going again is to restart the program even after restarting it will get stuck at merging chunks on the same stream if you try again so you have to move to another. The streams were tested outside the program and are okay it's only an issue within the program's download.  I've let it sit there in the "merging chunks" status for 15min and it didn't finish and so i can't see it being a waiting for it to finish problem. This has happened in both myqcloud streams and not so i don't think it's that either and sometimes a 2 hour stream will finish fine and then a 30min stream will be stuck at "merging chunks" and so i can't say it's based on length and it's happened on newer streams so can't say it's based on date. this doesn't count toward the stream download changing color after you restart the program when it's stuck on merging chunks.

There's also an issue with finished downloads cutting off a minute or two before the stream actually ends when played back confirmed using an outside source from the program and the programs internal download compared where the stream plays out 1-2 minutes longer to an end than it does when it's downloaded with the internal download which could also point to an issue with the merging of the chunks to where it's not finishing properly it cuts off before finished even when it does download this doesn't happen for every download but i have noticed it frequently it happens more than merging chunks getting stuck.

While i am here i would like to make a request. If there was an option to "mark as downloaded" to have a color change without downloading so you can mark off things easier that would be extremely helpful. It doesn't have to be that but just something you can manually mark to cut off streams you don't want to visit or already checked and don't care to go back again to help you from going over the same area.

thanksagain

**Comment by thecoder75** [comment] 2017-11-21 05:02
Duplicate of #107

**Comment by Hopeful13** [comment] 2017-11-21 07:58
Got this error a few times during the merging chunks process.

A JavaScript error occurred in the main process
Uncaught Exception
Error: spawn ENAMETOOLONG
at exports._errnoException
at exports.spawn
and a bunch of local temp app resources locations

**Comment by mmind99** [comment] 2017-11-21 14:10
I've seen this as well on my Win 10 system.  It doesn't happen very often and the next download generally goes ahead and starts even though it doesn't finish merging the previous chunks.  It has generally been on very large downloads when it has happened to me.  I had just assumed it was a corrupt video on the LiveMe end, which they are notorious for.  This does appear to be a different issue than 107 though.  In 107, it never makes it to merging chunks and it is also a 100% failure rate.  This issue is probably 1 out of 30 downloads for me.

**Comment by mmind99** [comment] 2017-11-21 14:58
Saw this happen again and checked the chunks afterwards.  There are several chucks that are just a couple kb and are 0 seconds long.  So its probably a corrupt file from LM that can't be merged.

**Comment by polydragon** [comment] 2017-11-21 17:01
Not a duplicate, it's related but different. It happens when there's a lot of chunks to combine and Windows cries that the length of the input filenames are too long. Fixed it locally but I'm waiting until I fixed the other issue to commit it.

**Comment by polydragon** [comment] 2017-11-21 19:22
Released version 7.0.2 which *should* fix this issue, closing.

**Closed by polydragon** 2017-11-21 19:22 UTC
Labels: duplicate
